name: "Add to PR Descriptions"
description: "Add to pull request descriptions using markdown"
author: "Derek Roberts"
branding:
  icon: "plus"
  color: "blue"

inputs:
  add_markdown:
    description: "Markdown message to use in PR description"
    required: true
  github_token:
    description: "GitHub token or a Personal Access Token (PAT)"
    default: ${{ github.token }}

runs:
  using: "node20"
  main: "dist/index.js"
